<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-NVQLMFJ" failures="1" tests="4" name="listener.NewTest" time="0.007" errors="0" timestamp="2024-01-05T09:24:32 IST" skipped="1">
  <testcase classname="listener.NewTest" name="d" time="0.003">
    <system-out>
      <![CDATA[TC d execution is started
Hi d is running
TC d is completed succesfull]]>
    </system-out>
  </testcase> <!-- d -->
  <testcase classname="listener.NewTest" name="a" time="0.003">
    <system-out>
      <![CDATA[TC a execution is started
Hi a is running
TC a is completed succesfull]]>
    </system-out>
  </testcase> <!-- a -->
  <testcase classname="listener.NewTest" name="b" time="0.001">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at listener.NewTest.b(NewTest.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
    <system-out>
      <![CDATA[TC b execution is started
TC b is failed, please check again]]>
    </system-out>
  </testcase> <!-- b -->
  <testcase classname="listener.NewTest" name="c" time="0.000">
    <skipped/>
    <system-out>
      <![CDATA[TC c is skipped, please check dependent]]>
    </system-out>
  </testcase> <!-- c -->
  <system-out>
    <![CDATA[TC f execution is started
Hi d is running
TC f is completed succesfull
TC e execution is started
Hi a is running
TC e is completed succesfull
TC g execution is started
TC g is failed, please check again
TC h execution is started
Hi c is running
TC h is completed succesfull
TC a execution is started
Hi a is running
TC a is completed succesfull
TC b execution is started
TC b is failed, please check again
TC d execution is started
Hi d is running
TC d is completed succesfull
TC c execution is started
TC c is skipped, please check dependent]]>
  </system-out>
</testsuite> <!-- listener.NewTest -->
